# Generated by Django 4.1.7 on 2023-04-11 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='group',
            new_name='team',
        ),
    ]
