# Generated by Django 4.1.7 on 2023-04-11 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabelApp', '0001_initial'),
        ('ProjectApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TeamApp', '0001_initial'),
        ('TaskApp', '0002_rename_group_tasks_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='_tasks', to='LabelApp.labels'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_tasks', to='ProjectApp.projects'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_tasks', to='TeamApp.teams'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
