# Generated by Django 4.1.7 on 2023-04-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0002_labelstasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabelsTasks',
        ),
    ]
