# Generated by Django 4.1.7 on 2023-04-11 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default='system', max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_expired', models.BooleanField(null=True)),
                ('logged_in_time', models.DateTimeField()),
                ('logged_out_time', models.DateTimeField(null=True)),
                ('is_revoked', models.BooleanField(null=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('token_type', models.CharField(choices=[('BEARER', 'Bearer')], default='BEARER', max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_login_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_details',
            },
        ),
    ]
